version: '3'
services:
  dealio-dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dealio-dashboard:v0.1
    container_name: dealio-dashboard
    networks:
      default:
        ipv4_address: 192.168.0.11
    ports:
      - "0.0.0.0:8080:8080"

networks:
  default:
    external:
      name: reverseproxy_nginx
